### ISSUE TITLE
Question: Install package

### ISSUE THREAD

**Issue by lingbopro** [Minemetero/LazyPy-School#1]
真的不需要用pip先装包吗…  

![Screenshot_20240617_112749.jpg](https://github.com/Minemetero/LazyPy-School/assets/148617407/5f32e029-1266-4e04-a577-92d034dbfa8e)

（代码以奇怪的方式…没跑起来…）

**Comment by lingbopro** [comment]
补充：

![Screenshot_20240617_113701_com.termux.jpg](https://github.com/Minemetero/LazyPy-School/assets/148617407/d3219c63-17a5-4404-aa5c-be3a0bc30b2d)

![Screenshot_20240617_113829_com.termux.jpg](https://github.com/Minemetero/LazyPy-School/assets/148617407/94775ff4-b1e9-403d-82ab-ffbe1cde1636)


在Termux的本地Linux环境依然跑不起来  
提示缺包

**Comment by Minemetero** [comment]
你要下载matplotlib啊

**Comment by Minemetero** [comment]
pip install matplotlib

**Comment by Minemetero** [comment]
你这个界面不像正常的windows.....

**Comment by lingbopro** [comment]
> 你这个界面不像正常的windows.....

当然了  
是tjy的win12啊

**Comment by Minemetero** [comment]
离谱

**Comment by lingbopro** [comment]
> 你要下载matplotlib啊

那你在README里说一声啊

**Comment by Minemetero** [comment]
win12 一个网页还可以跑Python？

**Comment by lingbopro** [comment]
> win12 一个网页还可以跑Python？

雀食可以  

内置了一个Python解释器，基于[Pyodide](https://pyodide.org/)

**Comment by lingbopro** [comment]
> > 你要下载matplotlib啊
> 
> 那你在README里说一声啊

@Minemetero

**Comment by Minemetero** [comment]
遥遥领先

**Comment by Minemetero** [comment]
代码没多长就是实现一些小功能

**Comment by lingbopro** [comment]
> 遥遥领先

6

**Comment by Minemetero** [comment]
> > 你要下载matplotlib啊
> 
> 那你在README里说一声啊

其实我没想着让其他人用，我不觉得别人会用。。。

**Comment by lingbopro** [comment]
> > > 你要下载matplotlib啊
> > 
> > 那你在README里说一声啊
> 
> 其实我没想着让其他人用，我不觉得别人会用。。。

e

**Comment by Minemetero** [comment]
我从来不自信。。。你现在在干啥？

**Comment by lingbopro** [comment]
> 我从来不自信。。。你现在在干啥？

我在去找我同学的路上:)

**Comment by Minemetero** [comment]
> > 我从来不自信。。。你现在在干啥？
> 
> 我在去找我同学的路上:)

抄家去了？你那个沉迷洛谷的同学？

**Comment by lingbopro** [comment]
> > > 我从来不自信。。。你现在在干啥？
> > 
> > 我在去找我同学的路上:)
> 
> 抄家去了？你那个沉迷洛谷的同学？

bushi，事另一个

**Comment by Minemetero** [comment]
我在等待我的第一个issue.....

**Comment by Minemetero** [comment]
PR

**Comment by lingbopro** [comment]
话说，其实turtle不用指出需要的  
Python自带

**Comment by Minemetero** [comment]
那你来改？我旅游回来了，那天北京天气好差

**Comment by lingbopro** [comment]
> 那你来改？我旅游回来了，那天北京天气好差

emmm
